# -----------------------------
# PostgreSQL Configuration File
# -----------------------------

# Connection Settings
listen_addresses = '*'
max_connections = 100

# Memory Settings
shared_buffers = 128MB                  # Minimum for small labs, but key to Module 1
work_mem = 4MB
maintenance_work_mem = 64MB

# Write-Ahead Log (WAL)
wal_level = replica                     # Essential for PITR (replica or logical)
fsync = on                              # Ensures changes are flushed to disk
synchronous_commit = on                 # We'll play with this in Module 2

# Checkpoints
checkpoint_timeout = 5min               # Range 30s to 1d
max_wal_size = 1GB
min_wal_size = 80MB
checkpoint_completion_target = 0.9      # Checkpoint effort distribution

# Archiving
archive_mode = on                       # Enabled for later modules
archive_command = 'cp %p /backups/wal/%f' # Copy WAL segment files to backup dir

# Logging
log_destination = 'stderr'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_statement = 'all'
log_line_prefix = '%m [%p] %q%u@%d '
